import type { CookieAttrs } from '../cookie-types';

export interface BokalExport {
  format: 'bokal-cookies';
  version: 1;
  exportedFrom?: string;
  cookies: CookieAttrs[];
}

export function toJson(cookies: CookieAttrs[], exportedFrom?: string): string {
  const payload: BokalExport = { format: 'bokal-cookies', version: 1, exportedFrom, cookies };
  return JSON.stringify(payload, null, 2);
}

export function toNetscape(cookies: CookieAttrs[]): string {
  const header = '# Netscape HTTP Cookie File\n# Generated by Bokal\n';
  const lines = cookies.map((c) => {
    const bareHost = c.domain.replace(/^\./, '');
    const domainField = c.hostOnly ? bareHost : `.${bareHost}`;
    const includeSub = c.hostOnly ? 'FALSE' : 'TRUE';
    const expiry = c.expirationDate !== undefined ? Math.floor(c.expirationDate) : 0;
    return [domainField, includeSub, c.path, c.secure ? 'TRUE' : 'FALSE', String(expiry), c.name, c.value].join('\t');
  });
  return header + (lines.length ? lines.join('\n') + '\n' : '');
}
